package com.tzh.retrofit_module.domain.model.bookIn

import androidx.compose.runtime.Immutable

@Immutable
data class BookInItem(
    val actualCalDate: String?,
    val airbase: String?,
    val airbaseId: String?,
    val basicDate: String?,
    val calDate: String?,
    val calDueDate: String?,
    val classification: String?,
    val csNo: Int,
    val ctk: String?,
    val ctkBox: String,
    val description: String,
    val docNo: String,
    val epc: String,
    val flight: String,
    val flightId: String?,
    val id: Int,
    val ipAddress: String?,
    val isBox: Boolean,
    val isCalRequired: Boolean,
    val issuerId: Int,
    val itemLocation: String,
    val itemStatus: String,
    val itemType: String,
    val itemTypeEnum: Int,
    val lastUpdatedDate: String?,
    val loanDueDate: String?,
    val nsn: String?,
    val otherBox: String?,
    val partNo: String,
    val qty: Int,
    val receiverId: Int,
    val remarks: String,
    val serialNo: String,
    val showCalAlert: Boolean,
    val storeLocation: String,
    val storeName: String,
    val storeType: String?,
    val tagQty: Int,
    val tagType: String?,
    val title: String,
    val tmdeBox: String?,
    val unit: String,
    val unitCost: String?,
    val unitId: String?,
    val updatedVersion: String?,
    val vendor: String?,
    val workLocation: String
)