object Dependencies {
    const val composeFoundationAndroid = "androidx.compose.foundation:foundation-android:${Versions.androidFoundation}"
    const val hiltWork = "androidx.hilt:hilt-work:${Versions.hiltCompiler}"
    const val hiltCompiler = "androidx.hilt:hilt-compiler:${Versions.hiltCompiler}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hiltAndroidCompiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    const val hiltNavigation = "androidx.hilt:hilt-navigation-compose:${Versions.hiltCompiler}"
    const val runtimeCompose = "androidx.lifecycle:lifecycle-runtime-compose:${Versions.runtimeCompose}"
    const val work = "androidx.work:work-runtime-ktx:${Versions.work}"
    const val accompanistPager = "com.google.accompanist:accompanist-pager:${Versions.accompanist}"
    const val accompanistPagerIndicator = "com.google.accompanist:accompanist-pager-indicators:${Versions.accompanist}"
    const val composeNavigation = "androidx.navigation:navigation-compose:${Versions.navCompose}"
    const val swipeBox = "io.github.kevinnzou:compose-swipebox:${Versions.swipeBox}"
    const val extendedMaterialIcons = "androidx.compose.material:material-icons-extended:${Versions.extendedMaterialIcons}"
    const val cryptoSecurity = "androidx.security:security-crypto:${Versions.cryptoSecurity}"
    const val composeConstraintLayout = "androidx.constraintlayout:constraintlayout-compose:${Versions.composeConstraintLayout}"
    const val composeSplashScreen = "androidx.core:core-splashscreen:${Versions.composeSplashScreen}"
    const val kotlinSerialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.kotlinSerialization}"

    const val dateStore = "androidx.datastore:datastore-preferences:${Versions.dataStore}"
    const val dateStoreCore = "androidx.datastore:datastore-preferences-core:${Versions.dataStore}"
    const val httpLoggingInterceptor =  "com.squareup.okhttp3:logging-interceptor:${Versions.httpLoggingInterceptor}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitGsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
}
